apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hw
  template:
    metadata:
      labels:
        app: hw
    spec:
      containers:
      - name: k8s-demo
        image: wardviaene/k8s-demo
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: nodejs-port 
          containerPort: 3000
      nodeSelector:
        hardware: high-spec