apiVersion: v1
kind: Pod
metadata:
  name: hellopod
  labels:
    name: hellopod
spec:
  containers:
    - name: hellopod
      image: wardviaene/k8s-demo
      ports:
        - name: contport
          containerPort: 3000
