apiVersion: v1
kind: Pod
metadata:
  name: hellopod
  labels:
    name: hellopod
spec:
  containers:
  - name: hellopod
    image: wardviaene/k8s-demo
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - name: nodejs-port
        containerPort: 3000
