apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hw-deployment
  template:
    metadata:
      labels:
        app: hw-deployment
    spec:
      containers:
      - name: hw-deployment
        image: wardviaene/k8s-demo
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
          name: nodejs-port
        volumeMounts:
        - name: cred-volume
          mountPath: /etc/creds
          readOnly: true
      volumes:
      - name: cred-volume
        secret:
          secretName: db-secrets